<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Email' => '',
    'How to calculate?' => 'Как рассчитывается?',
    'ID' => '',
    'Linked {client} account.' => '',
    'Password Reset Token' => '',
    'The calculation uses the sum of the salaries of all vacancies divided by the number of jobs with the specified salary.' => 'В рассчете используется сумма зарплат всех вакансий, деленная на количество вакансий с указанной зарплатой.',
    'Unable to link {client} account. There is another user using it.' => '',
    'Unable to link {client} account: {errors}' => '',
    'Unable to save user: {errors}' => '',
    'Unable to save {client} account: {errors}' => '',
    'User with the same email as in {client} account already exists but isn\'t linked to it. Login using email first to link it.' => '',
    'Index' => '@@@@',
    'Not set' => '@@@@',
    'Analytics' => 'Аналитика',
    'Auth Key' => 'Ключ авторизации',
    'Average salary' => 'Средняя зарплата',
    'Created At' => 'Создан',
    'Employment' => 'Занятность',
    'Enter vacancy name and press Enter' => 'Введите имя вакансии и нажмите Enter',
    'Enter your search phrase and press Enter' => 'Введите поисковую фразу и нажмите Enter',
    'External URL' => 'Внешняя ссылка',
    'From {from} to {to} {currency}' => 'От {from} до {to} {currency}',
    'From {from} {currency}' => 'От {from} {currency}',
    'Home' => 'Главная',
    'Indicators' => 'Показатели',
    'Login' => 'Вход',
    'Logout ({username})' => 'Выйти ({username})',
    'Max salary' => 'Максимальная зарплата',
    'Min salary' => 'Минимальная зарплата',
    'Not specified' => 'Не указана',
    'Password' => 'Пароль',
    'Password Hash' => 'Хэш пароля',
    'Remember me' => 'Запомнить меня',
    'Reset' => 'Сброс',
    'Resumes' => 'Резюме',
    'Salary' => 'Зарплата',
    'Schedule' => 'График работы',
    'Search' => 'Поиск',
    'Select industry of the company' => 'Выберите отрасль компании',
    'Select search area' => 'Выберите регион поиска',
    'Sign in' => 'Вход',
    'Sign in to your account' => 'Войти в аккаунт',
    'Sign in with {source}' => 'Войти через {source}',
    'Status' => 'Статус',
    'Submit' => 'Отправить',
    'The number of jobs with the specified salary' => 'Количество вакансий с указанной зарплатой',
    'The number of jobs with the specified salary percentage' => 'Количество вакансий с указанной зарплатой в процентах',
    'The total number of vacancies' => 'Общее количество вакансий',
    'To {to} {currency}' => 'До {to} {currency}',
    'Updated At' => 'Изменен',
    'Username' => 'Имя пользователя',
    'Vacancies' => 'Вакансии',
    'Vacancies search' => 'Поиск вакансий',
    'Vacancy Name' => 'Название вакансии',
    'detail' => 'подробнее',
];
