<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Area' => 'Регион',
    'Description' => 'Описание',
    'Email' => '',
    'ID' => '',
    'Industry' => 'Индустрия',
    'Linked {client} account.' => '',
    'Name' => 'Название',
    'Password Reset Token' => '',
    'Unable to link {client} account. There is another user using it.' => '',
    'Unable to link {client} account: {errors}' => '',
    'Unable to save user: {errors}' => '',
    'Unable to save {client} account: {errors}' => '',
    'User with the same email as in {client} account already exists but isn\'t linked to it. Login using email first to link it.' => '',
    'AND' => '@@И@@',
    'Enter vacancy name and press Enter' => '@@Введите имя вакансии и нажмите Enter@@',
    'Enter your search phrase and press Enter' => '@@Введите поисковую фразу и нажмите Enter@@',
    'OR' => '@@ИЛИ@@',
    'Analytics' => 'Аналитика',
    'Auth Key' => 'Ключ авторизации',
    'Average salary' => 'Средняя зарплата',
    'Created At' => 'Создан',
    'Employer' => 'Работодатель',
    'Employment' => 'Занятность',
    'External URL' => 'Внешняя ссылка',
    'From {from} to {to} {currency}' => 'От {from} до {to} {currency}',
    'From {from} {currency}' => 'От {from} {currency}',
    'Home' => 'Главная',
    'How to calculate?' => 'Как рассчитывается?',
    'Indicators' => 'Показатели',
    'Login' => 'Вход',
    'Logout ({username})' => 'Выйти ({username})',
    'Not found vacancies that match your search criteria' => 'Не найдено вакансий, соответствующих критериям поиска',
    'Not specified' => 'Не указана',
    'Password' => 'Пароль',
    'Password Hash' => 'Хэш пароля',
    'Remember me' => 'Запомнить меня',
    'Reset' => 'Сброс',
    'Resumes' => 'Резюме',
    'Salaries range' => 'Диапазон зарплат',
    'Salary' => 'Зарплата',
    'Schedule' => 'График работы',
    'Search' => 'Поиск',
    'Search all words' => 'Искать все слова',
    'Search any word' => 'Искать любое слово',
    'Search by description of vacancy' => 'Поиск по описанию вакансии',
    'Search by name of vacancy' => 'Поиск по названию вакансии',
    'Select industry of the company' => 'Выберите отрасль компании',
    'Select search area' => 'Выберите регион поиска',
    'Sign in' => 'Вход',
    'Sign in to your account' => 'Войти в аккаунт',
    'Sign in with {source}' => 'Войти через {source}',
    'Status' => 'Статус',
    'Submit' => 'Отправить',
    'The number of jobs with the specified salary' => 'Количество вакансий с указанной зарплатой',
    'The total number of vacancies' => 'Общее количество вакансий',
    'To {to} {currency}' => 'До {to} {currency}',
    'Updated At' => 'Изменен',
    'Username' => 'Имя пользователя',
    'Vacancies' => 'Вакансии',
    'Vacancies search' => 'Поиск вакансий',
    'Vacancy Name' => 'Название вакансии',
    'detail' => 'подробнее',
];
